version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:master
    networks:
      - kafka-net
    ports:
      - 49100:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: oxygen-0
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093

#  schema-registry:
#    image: bitnami/schema-registry:7.4.0
#    hostname: schema-registry
#    container_name: schema-registry
#    depends_on:
#      - zookeeper
#      - kafka
#    ports:
#      - "8090:8090"
#    networks:
#      - kafka-net
#    environment:
#      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8090
#      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9093

networks:
  kafka-net:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
